apiVersion: v1
kind: Secret
metadata:
  name: my-registry-key

data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJyZWdpc3RyeS5naXRsYWIuY29tIjogewoJCQkiYXV0aCI6ICJibUZtYVhWeWMyRnVNVHBDYWlGMFozSnZkWEF4IgoJCX0KCX0KfQ==
type: kubernetes.io/dockerconfigjson
